# SwiftLint Configuration for LuminaDex
# Professional-grade Swift code standards

# Directories to include/exclude
included:
  - LuminaDex
excluded:
  - Carthage
  - Pods
  - .build

# Enabled rules
opt_in_rules:
  - array_init
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Disabled rules
disabled_rules:
  - trailing_whitespace # We'll handle this with editor
  - todo # Allow TODO comments during development

# Custom rule configurations
line_length:
  warning: 120
  error: 150

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000

# Naming conventions
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

# Reporter format
reporter: "xcode"
